"""Type definitions for AIBrowserAutomation."""

from .models import (
    ActionType,
    EncodedId,
    ObserveResult,
    ActOptions,
    ActResult,
    ExtractOptions,
    ExtractResult,
    ObserveOptions,
    InitResult,
    ConstructorParams,
    AccessibilityNode,
    AgentAction,
    AgentResult,
    LLMUsage,
    CacheEntry,
)

from .browser import (
    Viewport,
    BrowserContextOptions,
    CDPSession,
    FrameInfo,
    DOMNode,
    NetworkRequest,
    Screenshot,
    MousePosition,
    KeyboardModifiers,
    BrowserEvent,
)

from .llm import (
    LLMMessage,
    LLMTool,
    LLMResponseFormat,
    LLMOptions,
    LLMUsageMetrics,
    LLMChoice,
    LLMResponse,
    LLMProviderConfig,
    ModelInfo,
    ProviderType,
    AnthropicCacheControl,
    AnthropicMessageBlock,
    GoogleSafetySettings,
    GoogleGenerationConfig,
)

__all__ = [
    # models.py
    "ActionType",
    "EncodedId",
    "ObserveResult",
    "ActOptions",
    "ActResult",
    "ExtractOptions",
    "ExtractResult",
    "ObserveOptions",
    "InitResult",
    "ConstructorParams",
    "AccessibilityNode",
    "AgentAction",
    "AgentResult",
    "LLMUsage",
    "CacheEntry",
    # browser.py
    "Viewport",
    "BrowserContextOptions",
    "CDPSession",
    "FrameInfo",
    "DOMNode",
    "NetworkRequest",
    "Screenshot",
    "MousePosition",
    "KeyboardModifiers",
    "BrowserEvent",
    # llm.py
    "LLMMessage",
    "LLMTool",
    "LLMResponseFormat",
    "LLMOptions",
    "LLMUsageMetrics",
    "LLMChoice",
    "LLMResponse",
    "LLMProviderConfig",
    "ModelInfo",
    "ProviderType",
    "AnthropicCacheControl",
    "AnthropicMessageBlock",
    "GoogleSafetySettings",
    "GoogleGenerationConfig",
]